# StandardRB Configuration
# For details, see https://github.com/testdouble/standard

plugins:
  - standard-rspec

# Enforce a maximum line length of 100 characters for Ruby files
max_line_length: 100

# File patterns to lint
patterns:
  - "lib/**/*.rb"
  - "test/**/*.rb"
  - "spec/**/*.rb"

ignore:
  - "spec/**/*":
    - "RSpec/VerifiedDoubles"
    - "RSpec/ExampleLength"
    - "RSpec/IndexedLet"
  - "spec/spec_helper.rb"
